create database amazon;
use amazon;
drop database amazon;
select * from sales;
SELECT * FROM sales WHERE YEAR(`Order Date`) = 2023;
select distinct Category,'Sub-Category' from sales order by Category,'Sub-Category';
select Sum(Amount)as total_Amount,Sum(Profit) as total_Profit from sales;
SELECT Category,SUM(Amount) AS Total_Amount FROM sales GROUP BY Category ORDER BY Total_Amount DESC;
SELECT Category,SUM(Category) AS Total_Category FROM sales GROUP BY Category ORDER BY Total_Category DESC;
select * from sales where profit < 0;
SELECT Category,AVG(Amount) AS Average_Amount,AVG(Profit) AS Average_Profit FROM sales GROUP BY Category;
SELECT PaymentMode,COUNT(*) AS Usage_Count FROM sales GROUP BY PaymentMode ORDER BY Usage_Count DESC LIMIT 1;
commit;
SELECT Category,SUM(Quantity) AS Total_Quantity FROM sales GROUP BY Category ORDER BY Total_Quantity DESC;
SELECT CustomerName,SUM(Amount) AS Total_Amount FROM sales GROUP BY CustomerName ORDER BY Total_Amount DESC LIMIT 10;
SELECT Category,'Sub-Category', SUM(Amount) AS Total_Amount, SUM(Profit)AS Total_Profit FROM sales GROUP BY Category,'Sub-Category'ORDER BY Total_Profit DESC;
SELECT 'Year-Month',SUM(Amount) AS Total_Amount FROM sales GROUP BY 'Year-Month' ORDER BY 'Year-Month';
SELECT YEAR('Order Date') AS Year,SUM(Amount) AS Total_Amount,SUM(Profit) AS Total_Profit FROM sales GROUP BY YEAR('Order Date')ORDER BY Year;
SELECT State,SUM(Profit) AS Total_Profit FROM sales GROUP BY State HAVING SUM(Profit) < 0 ORDER BY Total_Profit;
SELECT'Sub-Category',SUM(Profit) AS Total_Profit FROM sales GROUP BY 'Sub-Category'ORDER BY Total_Profit DESC LIMIT 5;
SELECT Category,SUM(Amount) AS Total_Revenue FROM sales GROUP BY Category ORDER BY Total_Revenue DESC LIMIT 1;
SELECT CustomerName,COUNT(*) AS Transaction_Count FROM sales GROUP BY CustomerName HAVING COUNT(*) > 3 ORDER BY Transaction_Count DESC;
SELECT PaymentMode,AVG(Quantity) AS Average_Quantity FROM sales GROUP BY PaymentMode ORDER BY Average_Quantity DESC;
SELECT City,SUM(Amount) AS Total_Amount FROM sales GROUP BY City ORDER BY Total_Amount DESC LIMIT 10;
SELECT'Sub-Category',SUM(Profit) AS Total_Profit FROM sales GROUP BY 'Sub-Category'HAVING SUM(Profit) > 10000 ORDER BY Total_Profit DESC;
SELECT CustomerName,SUM(Amount) AS Total_Amount,RANK() OVER (ORDER BY SUM(Amount) DESC) AS Customer_Rank FROM sales GROUP BY CustomerName;
 SELECT Category,'Sub-Category',SUM(Profit) AS Total_Profit FROM sales GROUP BY Category, 'Sub-Category';
 SELECT 'Order Date', SUM(Amount) Amount FROM sales GROUP BY 'Order Date';
 SELECT YEAR('Order Date') Year, SUM(Amount) Amount FROM sales GROUP BY Year;
 SELECT Category, 'Sub-Category', SUM(Amount) Amount,ROW_NUMBER() OVER(PARTITION BY Category ORDER BY SUM(Amount) DESC) r FROM sales GROUP BY Category, 'Sub-Category';
 SELECT 'Year-Month', SUM(Profit) Profit FROM sales GROUP BY 'Year-Month';
 SELECT CustomerName, SUM(Amount) Amount FROM sales GROUP BY CustomerName;
 SELECT Category, SUM(Amount) Amount,SUM(Profit) Profit FROM sales GROUP BY Category ORDER BY Profit DESC;
 SELECT State, SUM(Amount) Amount,SUM(Profit) Profit FROM sales GROUP BY State ORDER BY Profit DESC;
 SELECT 'Sub-Category', SUM(Amount) Amount,SUM(Profit) Profit FROM sales GROUP BY 'Sub-Category'ORDER BY Amount DESC;